#!/usr/bin/env python3
"""Fold the whole desk into one file somebody can run without a repository.

The verifier already clears this bar: drop a file on a page, no install, no
account, no terminal. The desk does not. Every conversation about trying it
ends with "clone the repo, work out which file, run Python", and most people
stop at the first clause.

Python itself is not the barrier -- macOS and Linux both ship it. The barrier
is the clone and the knowing-which-file. So this produces `dist/kya-desk.py`:
one stdlib-only file that runs from any directory.

    python3 tools/build-desk.py         build it
    python3 dist/kya-desk.py            run the desk, from anywhere
    python3 dist/kya-desk.py --sources  print every module it contains

Sources are base64 in the bundle, which is the only encoding that survives
arbitrary Python and HTML without escaping games -- every module here has a
docstring, so triple-quoting is out, and repr() of 160KB is one unreadable
line. `--sources` exists so the bundle is still inspectable: a single file
nobody can read is not obviously better than a repository nobody clones.
"""
import base64
import os
import subprocess  # nosec B404 - used once, to parse-check our own output
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "dist", "kya-desk.py")

# Import order matters: store imports kya_chain, server imports all of them.
MODULES = [
    ("kya_chain", "step-2-agent/kya_chain.py"),
    ("agent", "step-2-agent/agent.py"),
    ("bot", "step-6-whatsapp/bot.py"),
    ("meta", "step-7-providers/meta.py"),
    ("breet", "step-7-providers/breet.py"),
    ("store", "step-8-store/store.py"),
    ("desk_config", "step-9-desk/desk_config.py"),
]
SERVER = "step-5-operator/server.py"
PAGES = ["operator.html", "customer.html", "desk.html", "bot.html"]

HEAD = '''#!/usr/bin/env python3
"""KYA Rails desk -- the whole thing, in one file.

    python3 kya-desk.py              start it, then open http://localhost:8420/desk
    python3 kya-desk.py --ephemeral  do not save anything
    python3 kya-desk.py --devnet     use the real Canton ledger, not the mock
    python3 kya-desk.py --sources    print every module inside this file

Nothing to install. Python 3.8 or newer, which macOS and every Linux already
have. Settings live in desk.json beside wherever you run this; without one the
desk starts with a cap of zero and pays nobody, which is the safe reading of
"not set up yet".

GENERATED by tools/build-desk.py from https://github.com/dominicrume/cantor8_kya_rails
Do not edit this file: edit the repository and rebuild, or your change is lost
the next time somebody does.
"""
import base64 as _b64
import os as _os
import sys as _sys
import tempfile as _tempfile
import types as _types

_SOURCES = {}
_PAGES = {}
'''

TAIL = '''

def _unpack():
    """Register every bundled module, then serve the pages from a real folder.

    The server hands `directory=` to SimpleHTTPRequestHandler, so the pages have
    to exist somewhere on disk. Writing them to a temp folder keeps the server
    code identical to the repository's -- a bundle that needs its own serving
    path is a second implementation to keep in step, and it would drift.
    """
    for _name in _ORDER:
        _mod = _types.ModuleType(_name)
        _mod.__dict__["__name__"] = _name
        _mod.__dict__["__file__"] = _name + ".py"
        exec(compile(_b64.b64decode(_SOURCES[_name]).decode("utf-8"),
                     _name + ".py", "exec"), _mod.__dict__)   # nosec B102 - our own source
        _sys.modules[_name] = _mod

    _dir = _tempfile.mkdtemp(prefix="kya-desk-")
    for _n, _b in _PAGES.items():
        with open(_os.path.join(_dir, _n), "wb") as _f:
            _f.write(_b64.b64decode(_b))
    return _dir


def _sources():
    for _name in _ORDER + ["server"]:
        print("# " + "=" * 70)
        print("# %s" % _name)
        print("# " + "=" * 70)
        print(_b64.b64decode(_SOURCES[_name]).decode("utf-8"))
    return 0


def _main():
    if "--sources" in _sys.argv:
        return _sources()
    if "--example" in _sys.argv:
        # Same settings file the repository prints, from the bundle, so the
        # advice the desk gives when unconfigured is a command that exists.
        _unpack()
        import desk_config as _dc
        import json as _json
        print(_json.dumps(_dc.EXAMPLE, indent=2))
        return 0
    _dir = _unpack()
    _server = _types.ModuleType("server")
    _server.__dict__["__name__"] = "server"
    _server.__dict__["__file__"] = _os.path.join(_dir, "server.py")
    exec(compile(_b64.b64decode(_SOURCES["server"]).decode("utf-8"),
                 "server.py", "exec"), _server.__dict__)      # nosec B102 - our own source

    # The pages live in the temp folder; the journal and the settings belong
    # where the person running this is standing, not in a folder that vanishes.
    _server.HERE = _dir
    _server.DEFAULT_STORE = _os.path.join(_os.getcwd(), "kya-desk.db")
    return _server.main(_sys.argv[1:])


if __name__ == "__main__":
    _sys.exit(_main())
'''


def read(rel):
    with open(os.path.join(ROOT, rel), "rb") as f:
        return f.read()


def encoded(raw):
    """base64, wrapped so the generated file is not one 200KB line."""
    b = base64.b64encode(raw).decode("ascii")
    return "\n".join('    "%s"' % b[i:i + 76] for i in range(0, len(b), 76))


def build():
    out = [HEAD]
    for name, rel in MODULES + [("server", SERVER)]:
        out.append('_SOURCES["%s"] = (\n%s\n)\n' % (name, encoded(read(rel))))
    for page in PAGES:
        out.append('_PAGES["%s"] = (\n%s\n)\n'
                   % (page, encoded(read(os.path.join("step-5-operator", page)))))
    out.append("_ORDER = %r\n" % [n for n, _ in MODULES])
    out.append(TAIL)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("".join(out))
    # Executable on purpose: the whole point is `python3 kya-desk.py` or
    # ./kya-desk.py from anywhere. World-readable is correct for a file
    # meant to be handed to people; it contains no secret, and the secret
    # scan in the release preflight is what keeps that true.
    os.chmod(OUT, 0o755)  # nosec B103 - a distributable script, by design
    return os.path.getsize(OUT)


def main():
    size = build()
    print("wrote %s (%d KB, %d modules, %d pages)"
          % (os.path.relpath(OUT, ROOT), size // 1024, len(MODULES) + 1, len(PAGES)))
    r = subprocess.run([sys.executable, "-c",  # nosec B603 - our own interpreter
                        "import ast,sys;ast.parse(open(sys.argv[1]).read())", OUT],
                       capture_output=True, text=True)
    if r.returncode:
        print("  the generated file does not parse:\n" + r.stderr)
        return 1
    print("  it parses. Try:  python3 %s" % os.path.relpath(OUT, ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
