#!/usr/bin/env python3
"""A dated index of every public artefact, built from live sources.

Written for a Tech Nation Global Talent endorsement, but it is the document any
assessment needs: what exists, when it appeared, where to verify it, and what
each item actually demonstrates.

    python3 tools/evidence_pack.py > docs/evidence/index.md

GENERATED, NOT WRITTEN, and that is the point. An evidence pack typed by hand
goes stale the week after it is typed, and the one number nobody rechecks is
the one an assessor checks first. Every date and count below comes from the
GitHub API, the PyPI API or the Canton forum's public JSON at the moment this
runs. Anything unreachable is printed as unreachable rather than remembered.

Two things it deliberately does NOT do.

It does not score the application. Mapping an artefact to a criterion is a
judgement, and the judgements here are marked as such so a reader can disagree
with them without disagreeing with the facts.

It does not inflate. 189 downloads a month is 189 downloads a month. The rest
of this repository exists because of what happens when a number gets rounded in
its author's favour.
"""
import json
import os
import subprocess  # nosec B404 - fixed argv, no shell
import time
import sys
import urllib.request
from datetime import datetime, timezone

NOW = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
OWNER = "dominicrume"
REPO = "dominicrume/cantor8_kya_rails"


def gh(path):
    p = subprocess.run(["gh", "api", path],  # nosec B603 B607 - literal argv
                       capture_output=True, text=True, timeout=60)
    if p.returncode != 0:
        return None
    try:
        return json.loads(p.stdout)
    except ValueError:
        return None


def web(url, tries=3):
    """Read a JSON endpoint, retrying a rate limit rather than blanking a number.

    pypistats returns 429 under load. The first version treated that the same
    as unreachable and printed "download stats unreachable" into the evidence
    pack, which is a blank where a real figure exists. A transient failure that
    silently removes evidence is worse than one that stops.
    """
    last = None
    for attempt in range(tries):
        try:
            with urllib.request.urlopen(url, timeout=30) as r:  # nosec B310
                return json.loads(r.read())
        except Exception as e:               # noqa: BLE001 - unreachable is an answer
            last = e
            if attempt < tries - 1:
                time.sleep(2 * (attempt + 1))
    print("<!-- %s: %s -->" % (url, str(last)[:70]))
    return None


CACHE = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                     "..", "docs", "evidence", "downloads.json")


def downloads(name):
    """Download figures, cached with the date they were true.

    pypistats rate-limits hard, and a 429 was blanking a real number out of the
    evidence pack. A figure that vanishes because a third party was busy is a
    worse record than a figure carrying the date it was measured, which is what
    an evidence pack should contain anyway.
    """
    try:
        with open(CACHE) as f:
            cache = json.load(f)
    except (OSError, ValueError):
        cache = {}
    live = web("https://pypistats.org/api/packages/%s/recent" % name, tries=2)
    if live:
        cache[name] = {"month": live["data"]["last_month"],
                       "week": live["data"]["last_week"],
                       "measured": datetime.now(timezone.utc).strftime("%Y-%m-%d")}
        os.makedirs(os.path.dirname(CACHE), exist_ok=True)
        with open(CACHE, "w") as f:
            json.dump(cache, f, indent=2, sort_keys=True)
    got = cache.get(name)
    if not got:
        return "download figures not yet measured"
    return ("%s downloads in the last month, %s in the last week, measured %s"
            % (got["month"], got["week"], got["measured"]))


def row(date, what, url, shows, crit):
    return "| %s | %s | %s | %s | %s |" % (date, what, url, shows, crit)


print("# Evidence index")
print()
print("Every public artefact, with the date it appeared and where to verify it.")
print()
print("Generated by `tools/evidence_pack.py` on **%s** from the GitHub, PyPI "
      "and Canton forum APIs. Regenerate before submitting anything: numbers "
      "move, and a stale figure is the one an assessor checks first." % NOW)
print()
print("Criterion codes are Tech Nation's: **MC** mandatory, **OC1** innovation, "
      "**OC2** recognition beyond occupation, **OC4** academic contribution. "
      "The mapping is a judgement and is marked as one. The dates are facts.")
print()

# ------------------------------------------------------------------ published
print("## Published software")
print()
print("| first published | package | where | what it shows | maps to |")
print("|---|---|---|---|---|")
for name, note in (("knowyouragenticai-receipts",
                    "A receipt format with a written specification. Zero "
                    "dependencies, MIT."),
                   ("ai-code-quality-auditor",
                    "MSc dissertation tool. The longer track record of the two.")):
    d = web("https://pypi.org/pypi/%s/json" % name)
    if not d:
        print(row("?", name, "unreachable", note, "OC1"))
        continue
    rels = d["releases"]
    first = min((f["upload_time_iso_8601"][:10]
                 for v in rels for f in rels[v] if f.get("upload_time_iso_8601")),
                default="?")
    used = downloads(name)
    print(row(first, "`%s` %s, %d releases" % (name, d["info"]["version"], len(rels)),
              "pypi.org/project/%s/" % name,
              "%s %s." % (note, used),
              "OC1" if "receipts" in name else "OC1, OC4"))
print()

# ----------------------------------------------------------- contributions
print("## Contributions to projects owned by other people")
print()
print("The strongest section, because none of it is self-published and all of "
      "it is timestamped by somebody else's system.")
print()
print("| opened | contribution | where | what it shows | maps to |")
print("|---|---|---|---|---|")
CONTRIB = [
    ("OpenZeppelin/canton-contracts", 43,
     "Three authorisation fences with no test behind them, in OpenZeppelin's "
     "Canton library. Reproduced from a clean clone."),
    ("OpenZeppelin/canton-token-template", 9,
     "24 of 32 fences could be made vacuous with every test still passing."),
    ("OpenZeppelin/canton-stablecoin", 9,
     "25 of 30, including the oracle price guard."),
    ("canton-network-devs/Canton-Developer-Hub", 156,
     "Listed in the official Canton Developer Hub tool catalogue."),
    ("canton-network-devs/Canton-Developer-Hub", 160,
     "A fix for link rendering affecting nineteen catalogue entries, only one "
     "of which is ours."),
]
for repo, num in [(c[0], c[1]) for c in CONTRIB]:
    note = next(c[2] for c in CONTRIB if c[0] == repo and c[1] == num)
    d = gh("/repos/%s/issues/%d" % (repo, num))
    if not d:
        print(row("?", "%s#%d" % (repo.split("/")[-1], num), "unreachable", note, "OC2"))
        continue
    merged = (d.get("pull_request") or {}).get("merged_at")
    state = "merged %s" % merged[:10] if merged else d["state"]
    print(row(d["created_at"][:10],
              "%s#%d, %s" % (repo.split("/")[-1], num, state),
              d["html_url"], note, "OC2"))
print()

# ------------------------------------------------------------------- forum
print("## Public technical discourse")
print()
print("Archived in `docs/evidence/archive/` as both the raw API response and a "
      "readable rendering, because forum posts can be edited or deleted and an "
      "assessor may read this months later.")
print()
print("| date | exchange | where | what it shows | maps to |")
print("|---|---|---|---|---|")
for tid, note, crit in (
        (9114,
         "An independent engineer reviewed the architecture unprompted, "
         "identified that application-written receipts cannot prove "
         "completeness, and specified the fix. It was implemented the next day "
         "and he was credited publicly, in the thread, by name.", "MC, OC2"),
        (9059,
         "A stablecoin issuer building on Canton engaged with the work across "
         "several exchanges. Also carries the findings report on OpenZeppelin's "
         "test suites.", "OC2")):
    d = web("https://forum.canton.network/t/%d.json" % tid)
    if not d:
        print(row("?", "forum t/%d" % tid, "unreachable", note, crit))
        continue
    posts = d["post_stream"]["posts"]
    print(row(posts[0]["created_at"][:10],
              "%s, %d posts, %d views" % (d.get("title", "")[:44], len(posts),
                                          d.get("views", 0)),
              "forum.canton.network/t/%d" % tid, note, crit))
print()

# ------------------------------------------------------------------- the work
print("## The work itself")
print()
print("| since | artefact | where | what it shows | maps to |")
print("|---|---|---|---|---|")
r = gh("/repos/%s" % REPO)
first = subprocess.run(  # nosec B603 B607
    ["git", "log", "--reverse", "--pretty=%ad", "--date=short"],
    capture_output=True, text=True).stdout.splitlines()
commits = subprocess.run(  # nosec B603 B607
    ["git", "rev-list", "--count", "HEAD"],
    capture_output=True, text=True).stdout.strip()
if r:
    print(row(first[0] if first else "?",
              "%s, %s commits" % (REPO.split("/")[-1], commits),
              r["html_url"],
              "A Daml package on Canton DevNet, a receipt library, a browser "
              "verifier, and a test suite that breaks its own checks to prove "
              "they hold. %s stars, %s forks."
              % (r["stargazers_count"], r["forks_count"]),
              "OC1"))
print(row("2026-09-06", "Specification and conformance vectors",
          "github.com/%s/blob/main/SPEC.md" % REPO,
          "Three independent implementations in Python, JavaScript and Go "
          "agree on 20 conformance vectors. A format two people implement is a "
          "library; one that three implement is closer to a standard.", "OC1"))
print(row("2026-09-12", "Verifiable in a browser with nothing installed",
          "dominicrume.github.io/cantor8_kya_rails/",
          "A regulator can check a disclosure file with no wallet, no account "
          "and no network.", "OC1"))
print()

print("## What this does not yet show")
print()
print("Stated here so it is not discovered by someone else.")
print()
print("- **No recommendation letters.** Three are needed, from senior people "
      "in the field. The relationships that could produce one are days old. "
      "Asking now would spend them.")
print("- **Adoption is early.** Hundreds of downloads a month, not thousands, "
      "and nobody outside this project has yet produced a chain with the "
      "format. That is written into the repository too.")
print("- **The Canton work is weeks old.** The depth is in the auditor, first "
      "published 31 May 2026, and in the MSc behind it. Lead with the arc, not "
      "the fortnight.")
print()
print("*Regenerate with `python3 tools/evidence_pack.py > docs/evidence/index.md`.*")
